# Generated by Django 4.0.3 on 2022-07-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asched', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientattribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdatetime', models.DateField(auto_now_add=True)),
                ('background', models.CharField(choices=[('simple', 'simple'), ('transparent', 'transparent')], max_length=20)),
                ('fileformat', models.CharField(choices=[('TIFF', 'TIFF'), ('PDF', 'PDF'), ('PNG', 'PNG')], max_length=20)),
                ('totalpricetopay', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='clientbasicinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_surname', models.CharField(max_length=200, null=True)),
                ('cl_firstname', models.CharField(max_length=200, null=True)),
                ('cl_middlename', models.CharField(max_length=200, null=True)),
                ('cl_email', models.EmailField(max_length=200)),
                ('cl_contact', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='portraitshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot', models.CharField(choices=[('wholebody', 'wholebody'), ('headshot', 'headshot'), ('bust', 'bust'), ('halfbody', 'halfbody')], max_length=20)),
                ('shot_price', models.CharField(max_length=200)),
                ('art', models.CharField(choices=[('chibi style', 'chibi style'), ('pixel art', 'pixel art'), ('anime style', 'anime style'), ('vector art', 'vector art')], max_length=20)),
                ('art_price', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('sketch', 'sketch'), ('black&white', 'black&white'), ('full color', 'full color')], max_length=20)),
                ('color_price', models.CharField(max_length=200)),
                ('sizes', models.CharField(choices=[('3508 x 2480 px', '3508 x 2480 px'), ('3300 x 2550 px', '3300 x 2550 px'), ('2000 x 2000 px', '2000 x 2000 px')], max_length=20)),
                ('size_price', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
        migrations.AddField(
            model_name='clientattribute',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asched.clientbasicinfo'),
        ),
    ]
