# Generated by Django 4.0.3 on 2022-07-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asched', '0003_alter_clientattribute_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientattribute',
            name='background',
            field=models.CharField(choices=[('simple', 'simple'), ('transparent', 'transparent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientattribute',
            name='fileformat',
            field=models.CharField(choices=[('TIFF', 'TIFF'), ('PNG', 'PNG'), ('PDF', 'PDF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientbasicinfo',
            name='cl_contact',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='portraitshot',
            name='art',
            field=models.CharField(choices=[('chibi style', 'chibi style'), ('vector art', 'vector art'), ('anime style', 'anime style'), ('pixel art', 'pixel art')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portraitshot',
            name='color',
            field=models.CharField(choices=[('sketch', 'sketch'), ('full color', 'full color'), ('black&white', 'black&white')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portraitshot',
            name='shot',
            field=models.CharField(choices=[('bust', 'bust'), ('halfbody', 'halfbody'), ('headshot', 'headshot'), ('wholebody', 'wholebody')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portraitshot',
            name='sizes',
            field=models.CharField(choices=[('3300 x 2550 px', '3300 x 2550 px'), ('2000 x 2000 px', '2000 x 2000 px'), ('4000 x 4000 px', '4000 x 4000 px')], max_length=20),
        ),
    ]
