# Generated by Django 4.0.3 on 2022-07-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asched', '0005_alter_clientattribute_fileformat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientattribute',
            name='totalpricetopay',
        ),
        migrations.AlterField(
            model_name='clientattribute',
            name='background',
            field=models.CharField(choices=[('transparent', 'transparent'), ('simple', 'simple')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientattribute',
            name='fileformat',
            field=models.CharField(choices=[('TIFF', 'TIFF'), ('PDF', 'PDF'), ('PNG', 'PNG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portraitshot',
            name='art',
            field=models.CharField(choices=[('vector art', 'vector art'), ('anime style', 'anime style'), ('pixel art', 'pixel art'), ('chibi style', 'chibi style')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portraitshot',
            name='color',
            field=models.CharField(choices=[('sketch', 'sketch'), ('black&white', 'black&white'), ('full color', 'full color')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portraitshot',
            name='shot',
            field=models.CharField(choices=[('headshot', 'headshot'), ('wholebody', 'wholebody'), ('halfbody', 'halfbody'), ('bust', 'bust')], max_length=20),
        ),
        migrations.AlterField(
            model_name='portraitshot',
            name='sizes',
            field=models.CharField(choices=[('3300 x 2550 px', '3300 x 2550 px'), ('2000 x 2000 px', '2000 x 2000 px'), ('4000 x 4000 px', '4000 x 4000 px')], max_length=20),
        ),
    ]
